server:
  port: 8001
  
  
spring:

  application:
    name: User-Service
  
  datasource:
    url: jdbc:mysql://localhost:3306/UserService
    username: root    
    password: root
    

    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  config:
    import: optional:configserver:http://localhost:8010
    
  profiles:
    active: default
    
    
    
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
        
  endpoint:
    health:
      show-details: always    



    
UserCredentials:
  datasource:
    url: jdbc:mysql://localhost:3306/user_credentials
    username: root
    password: root
    
resilience4j:
  circuitbreaker:
    instances:
      HotelRatingBreaker: 
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        

          
          
          
    
    
    
    
