server:
  port: 8003
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/RatingService
    username: root
    password: root
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  application:
    name: Rating-Service
    
  config:
    import: configserver:http://localhost:8010
  profiles:
    active: default